site_name: EPSO AD5 2026 Simulator
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Simulator: quiz.html
    - Teoria:
    - Panoramica: theory/index.md
    - Istituzioni UE: theory/institutions.md
    - Processo legislativo (OLP): theory/olp.md
    - Trattati e diritto UE: theory/treaties_law.md
    - Bilancio UE: theory/budget.md
    - Politiche UE essenziali: theory/policies.md
    - Digital skills (DigComp): theory/digcomp.md
    - Glossario: theory/glossary.md
  
